# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 824)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_c = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_c.setGeometry(QtCore.QRect(570, 480, 41, 25))
        self.checkBox_c.setObjectName("checkBox_c")
        self.checkBox_a = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_a.setGeometry(QtCore.QRect(570, 400, 41, 25))
        self.checkBox_a.setObjectName("checkBox_a")
        self.checkBox_b = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_b.setGeometry(QtCore.QRect(570, 440, 41, 25))
        self.checkBox_b.setObjectName("checkBox_b")
        self.checkBox_z = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_z.setGeometry(QtCore.QRect(570, 190, 41, 25))
        self.checkBox_z.setObjectName("checkBox_z")
        self.checkBox_x = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_x.setGeometry(QtCore.QRect(570, 110, 41, 25))
        self.checkBox_x.setObjectName("checkBox_x")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 70, 151, 31))
        self.pushButton.setObjectName("pushButton")
        self.checkBox_y = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_y.setGeometry(QtCore.QRect(570, 150, 41, 25))
        self.checkBox_y.setObjectName("checkBox_y")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(50, 30, 88, 27))
        self.saveButton.setObjectName("saveButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(50, 70, 151, 41))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(710, 20, 121, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(700, 320, 121, 19))
        self.label_2.setObjectName("label_2")
        self.MplWidget_2 = MplWidget(self.centralwidget)
        self.MplWidget_2.setGeometry(QtCore.QRect(620, 350, 381, 231))
        self.MplWidget_2.setObjectName("MplWidget_2")
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setGeometry(QtCore.QRect(620, 50, 381, 231))
        self.MplWidget.setObjectName("MplWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_c.setText(_translate("MainWindow", "z"))
        self.checkBox_a.setText(_translate("MainWindow", "x"))
        self.checkBox_b.setText(_translate("MainWindow", "y"))
        self.checkBox_z.setText(_translate("MainWindow", "z"))
        self.checkBox_x.setText(_translate("MainWindow", "x"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.checkBox_y.setText(_translate("MainWindow", "y"))
        self.saveButton.setText(_translate("MainWindow", "Save CSV"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Sans\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">filename.csv</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Accelerometer"))
        self.label_2.setText(_translate("MainWindow", "Gyroscope"))
from mplwidget import MplWidget
